### ISSUE TITLE
Duplicate Build entries in Builds tab

### ISSUE THREAD

**Issue by m-Pawlowicz** [argos-ci/argos#1312]
Hi, I've experienced that the exact same commit triggers an argos build twice. The duplicate one results in no screenshots. 

![image](https://github.com/argos-ci/argos/assets/152787691/9338a092-f1ee-4670-84e1-8f13aa9de0b4)

As you can see there are four entries with two duplicates. Each original - duplicate entry references the same commit SHA.

This is my github action config file

```yaml
name: Cypress

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      

jobs:
  cypress:
    runs-on: ubuntu-latest
    environment: production
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
      CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}

    steps:
      - name: "list env"
        run: env

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: enable corepack
        run: corepack enable

      - name: install yarn
        run: "corepack prepare yarn@3.8.2 --activate"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          browser: chrome

      - name: Upload screenshots to argos-ci.com
        run: yarn run argos upload ./screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
```
### Question
Am i missing something? Any help would be appreciated.

Ps. 
I am enjoying argos so far, though some parts of the docs are a bit vague, happy to raise a pr whenever i'll have some time
